import string
import math

ciph="kdIeccehdoaunrtoIasifewegasinbwebttedcuhowtrohmeiiaefsndmttyeeplcuydIaonerlthdanigathnnydsosiuetkdoucIedondntoiwtesctphesduernideaethotfeobThlteihpshwgaihlolysphgeitdawusrefalcohletotptiegeehdnacnikgeposapirtteaedchheoctrecnhrlnTuemoiesnwvamcsleiebmohisatnstsgeutgwshitaatigathnnyhnmetoareripptaaegeobdatokrdwarnattleatbtehenercadogrfnaorctrolnuhoIposmeaeokddptnnisdelaoeordnfehtrmhcebtasmnuiwstrehaenmnhiogtiaeancchIolattchnTufilddcehhiektfhngoitnntepatdokfhuleoblmtcohuelondadlifrwomroolsairfyaniutabtshnaeclamogithsumukhdtacnnhepidtuweeldfhotprheeotdhjneotimtelucnoaahewesrmtsllmeatbalalepgmeinaarmrarskaeatkheMryetsppkdirohooetdaotShhdeiewchAvreacriadrapsilirmncleiastwtrediibrdhettahoJerkmfantoTahnnkmhocesloaiwhtmhtrnacuufscehedetssutyryitetonehmneeranctkdIootelealehihkmddsoaaltbeistahanlewesHriofutnaaetemukrhrrdtaendneulcoonrleoyebhheonaesehaaddtmIminestoprubesatoktalocfnsmhaeicshmwaHteigeadlneaesemakfcorViitnodrnLinaiBondnfaaflkhadceeethlnthmeordiflatuiodbnhseiatftfearhoeaotShhdeiewchAvrloioutdcbcnbeleyhraetuesscereweehtrsteatodweteorefaevrnkscoheretotutyrfihvhrceiAlMeseifthsaetyibtyihasmwkraactetalwrealsrnyteaaftedsoihftuydshratocaykowsosnIohoakuthlndeltmrhaehulityowhntacmiyIogadhwevbuhaledlkeuneindsetoliyTnceroavhnnecsamthibustmuhahotgtnetmirdeasdIwmseuntlvilleoeblrdahswntneisdhowaIdhnittdineakertwhnesyoaenonlarsuecudtIboueultbdsnIerndenaakedbdceinuntplUrhohewetenatbdenhoeugntorygHaertvdiolnevsdihinatrIvtueenwsslltaitinertachwnattehelodbualthledoowtseoulapteIsnwraueayslrlaittnhtaeuolsncaairywistebnlvvdosbuwataIeysutollihctaenrdaeulwwoetnostetedhInieseoeogdtteyuaftlsmbaconedtaawichkoetmsewapocldoruepplyexrhAletoerenrivcahotdndfuihTwttheafsasanenBftedoeretoIlrfeoeIoktnookmeloordaaunrgonttrihgeppheweafawethrtsfaelertetnnutdipoegectdheubksoconoryietleoackptocpfbamkytlaIscikdtlulcnovtbieeelathmyattsaaerchkibdftltebtendhuiptphaesrsehmiesytedinihtitgomlnoxihreecitotenetmrhgheattrmevegnoprepanethhsicwthfueadyohohnfndtIscielnegtfaoumoewstsIhaiitctaenreohthactkadooewbhesrtwroIaangdhididhanttnpmoiestpoeitcrtbtplyeurcitsehtehVontneorcinegeeloierpohslkabeodfsulytaeigcatinn"
cipher=""
key=8
alpha=[i for i in string.ascii_letters]
plaintext=""
for i in ciph:
    if i in alpha:
        cipher+=i
order=[2,5,7,3,4,0,6,1]
orderstring=""
count=0
plaintext=""

#{4: 2, 5: 3, 2: 5, 6: 4, 0: 7, 1: 6, 3: 6}
for i in range(0,int(len(cipher)/key)):
    for j in order:
        plaintext+=cipher[count+j]
    count+=key
for i in order:
    orderstring+=str(i)
print(plaintext)

